version: '3'
services:
  admiral_server:
    build:
      context: .
      args:
          - PORT=${PORT}
    image: admiral-api
    depends_on:
      - admiral_database
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
    ports:
      - 3001:${PORT}
    container_name: 'admiral_api'
    networks:
      - admiral_net
  admiral_database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    container_name: 'admiral_db'
    networks:
      - admiral_net
networks:
  admiral_net:
    driver: bridge